apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cal-app
  template:
    metadata:
      labels:
        app: cal-app
    spec:
      containers:
      - name: cal-app
        image: thipparthiavinash/2048-game
        ports:
        - containerPort: 80
