apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-app-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cal-app
  template:
    metadata:
      labels:
        app: cal-app
    spec:
      containers:
      - name: cal-app
        image: 828477980115.dkr.ecr.ap-south-1.amazonaws.com/awar04-calapp:latest
        ports:
        - containerPort: 80