apiVersion: v1
kind: Namespace
metadata:
  name: uat-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-deploy
  namespace: uat-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cal-app
  template:
    metadata:
      labels:
        app: cal-app
    spec:
      containers:
      - name: cal-app
        image: 828477980115.dkr.ecr.ap-south-1.amazonaws.com/awar04-calapp:latest
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: cal-service
  namespace: uat-namespace
spec:
  selector:
    app: cal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer