apiVersion: v1
kind: LimitRange
metadata:
  name: dev-ns-limit
  namespace: dev-namespace
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "0.5"
      memory: "512Mi"
    type: Container