apiVersion: v1
kind: Pod
metadata:
  name: test-pod-success
  namespace: dev-namespace
spec:
  containers:
  - name: cal-container
    image: 828477980115.dkr.ecr.ap-south-1.amazonaws.com/awar04-calapp:latest
    resources:
      requests:
        memory: "512Mi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"
    ports:
    - containerPort: 80