# This IngressClass manifest configures AWS Application Load Balancer (ALB) as the default ingress controller
# for the Kubernetes cluster. It enables automatic creation and management of ALBs for ingress resources.
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: eks.amazonaws.com/alb
